language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- echo "Run tests here"
#- ./run_tests.sh
before_deploy:
- BRANCH=$(echo "$TRAVIS_BRANCH" | tr / _) # remove '/' from branch name
- cd ..; zip from_travis_$BRANCH.zip lambda_function.py
deploy:
  provider: lambda
  access_key_id: AKIAIKM5YAHQGFDE72SQ
  secret_access_key:
    secure: ZTcjEHtJnAM39kLA55EiePoqZncTPeEZNTFX7E5xkc3TLAqgJlpjpoH40Qq7cn5gzdZ0Z9YWlOCyIV0Va6Oxc7XJVK/lSzioelseKnz+yscUq8aAJluy1INx7uXEbiPwRNz+bfy5uYOU/Bn/+6/I4Wc3MbvNRdbwF57hXdn6WjD7s+/T65l2PL3iN4MqLRmzuC+BRztOugnWM6s/za7pcA7AP9j367HX0yt/31h9CPIZuGFSItWjmxEFAB7VfCqN+fF7ZisOwGRDJkzzEv6eJbpsCq1m1Jl3TYfQoX96mUh0Pa2frk69enDVSsOkDeQ82DrREf51wdfk6Gs/YmrrVSoaBM0Cm97Ssd7fr2erxTlIdfRvPDN3vncWzsnvVZHkez2owqWV9TEaAgbVsI6myINAX0Ibh8beLkCHjFLXYoOBglNGrc2DC2M9ZBpM18nJ2tZVAva2t53MSFtcRw06xu4E9+ZBMZeVacXM1BA7M6APQVSDwrHJk3BVgaz+Wi+iUFZkmCujI5xS1PNta+iVZ6yJyiMd2l2oLsikcs9qYI94aZvmHYFSxq+LdZfIpov/10dPt800jHDgszKcGJ4rGGZOTFguI7fDPrkkTgihLthRuBGc5umMI4hdJZ4CB1JXCkWK/wk7hdBuMye7VzAEc9XfFflAUb+3H7T1PfhC+MM=
  function_name: "from_travis_${BRANCH}"
  region: "us-east-2"
  role: "arn:aws:iam::707767160287:role/dos-indexd-lambda-dev"
  runtime: "python3.6"
  publish: true # create a new version of the lambda function
  zip: "from_travis_${BRANCH}.zip"
  handler_name: "lambda_function.lambda_handler"
  skip_cleanup: true
  on:
    branch: test/travis
